<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Iced" Version="1.21.0" />
    <Compile Include="../God2.OfflineClientReverseEngineering/BoundedFile.cs" Link="BoundedFile.cs" />
  </ItemGroup>
</Project>
