using System.Security.Cryptography;
using System.Text;
using God2.LoginServerRoundTrip;

const string boundary = "FORMAT ONLY: Does not prove that the 6F2639… original client accepts new files or establish endpoint precedence. No client, launcher, TCP or DB operations; all generated bytes remain in memory.";
Console.WriteLine(boundary);
try
{
    if (args.Length == 1 && args[0] == "--self-test")
    {
        SelfTests.Run();
        return 0;
    }
    PackedRoundTrip.Require(args.Length == 0, "Use no arguments from the repository root, or --self-test.");
    var assets = new[]
    {
        (Path: "src/God2.V2Launcher/Resources/LoginServer.v2.csvZ", Hash: "AC25B908EBC02C280AE8BDB713990486B06CA57258B2035202FB386BC64ABB85", Packed: 240, Plain: 207,
            Patches: new[] { (Ip: "52.63.34.162", Count: 2) }),
        (Path: "/srv/god2-reference/client-legacy/God2/LoginServer.csvZ", Hash: "C5AA8124DB417D13548182DF83F6D44EF74EA6292747AB1997E9B14557525170", Packed: 226, Plain: 208,
            Patches: new[] { (Ip: "203.69.83.72", Count: 1), (Ip: "118.26.233.73", Count: 1) })
    };
    foreach (var asset in assets)
    {
        using var input = new FileStream(asset.Path, FileMode.Open, FileAccess.Read, FileShare.Read);
        PackedRoundTrip.Require(input.Length == asset.Packed, "Unexpected asset length.");
        var original = new byte[asset.Packed];
        input.ReadExactly(original);
        PackedRoundTrip.Require(Convert.ToHexString(SHA256.HashData(original)) == asset.Hash,
            "Asset hash mismatch; refusing unknown input.");
        var plain = PackedRoundTrip.Decode(original, asset.Packed, asset.Plain, 0x5A);
        PackedRoundTrip.Verify(plain, PackedRoundTrip.Encode(plain, original[6]), original[6]);
        var changed = plain.ToArray();
        foreach (var patch in asset.Patches)
            changed = PackedRoundTrip.Patch(changed, patch.Ip, 6001, "127.0.0.1", 6002, patch.Count);
        PackedRoundTrip.Verify(changed, PackedRoundTrip.Encode(changed, original[6]), original[6]);
        // The input stays read-only and its bytes must remain unchanged.
        input.Position = 0;
        var after = new byte[asset.Packed];
        input.ReadExactly(after);
        PackedRoundTrip.Require(after.AsSpan().SequenceEqual(original), "Original asset changed.");
        Console.WriteLine($"PASS: {asset.Path}; marker=0x5A; original round-trip and ASCII endpoint patch round-trip; original bytes unchanged.");
    }
    return 0;
}
catch (Exception exception) when (exception is InvalidDataException or IOException or ArgumentException or OverflowException)
{
    Console.Error.WriteLine($"FAIL: {exception.Message}");
    return 1;
}

internal static class SelfTests
{
    internal static void Run()
    {
        var plain = Encoding.ASCII.GetBytes("LoginServer,1\r\n1,name,52.63.34.162 asdf 6001\r\n");
        var packed = PackedRoundTrip.Encode(plain, 0x5A);
        PackedRoundTrip.Verify(plain, packed, 0x5A);
        foreach (var length in new[] { 1, 7, 8, 9, PackedRoundTrip.MaximumPayload })
        {
            var bytes = Enumerable.Range(0, length).Select(i => (byte)i).ToArray();
            PackedRoundTrip.Verify(bytes, PackedRoundTrip.Encode(bytes, 0x5A), 0x5A);
        }
        var changed = PackedRoundTrip.Patch(plain, "52.63.34.162", 6001, "127.0.0.1", 6002, 1);
        PackedRoundTrip.Require(changed.AsSpan().SequenceEqual(Encoding.ASCII.GetBytes(
            "LoginServer,1\r\n1,name,127.0.0.1 asdf 6002\r\n")), "Patch test mismatch.");
        foreach (var endpoint in new[] { (Ip: "127.0.0.1", Port: 6001), (Ip: "52.63.34.162", Port: 6002) })
        {
            byte[] opaque = [0xAE, 0xFF, ..plain, 0x00, 0x81];
            var result = PackedRoundTrip.Patch(opaque, "52.63.34.162", 6001, endpoint.Ip, endpoint.Port, 1);
            byte[] expected = [0xAE, 0xFF, ..Encoding.ASCII.GetBytes(
                $"LoginServer,1\r\n1,name,{endpoint.Ip} asdf {endpoint.Port}\r\n"), 0x00, 0x81];
            PackedRoundTrip.Require(result.AsSpan().SequenceEqual(expected), "IP/port-only or opaque byte test mismatch.");
            PackedRoundTrip.Verify(result, PackedRoundTrip.Encode(result, 0x5A), 0x5A);
        }
        var cases = 0;
        void Reject(string label, Action action)
        {
            try { action(); }
            catch (InvalidDataException) { cases++; Console.WriteLine($"PASS reject: {label}"); return; }
            throw new InvalidDataException($"Did not stop safely: {label}");
        }
        foreach (var index in new[] { 0, 1, 6 })
        {
            var bad = packed.ToArray(); bad[index] ^= 1;
            Reject($"header byte {index}", () => PackedRoundTrip.Decode(bad, packed.Length, plain.Length, 0x5A));
        }
        Reject("short header", () => PackedRoundTrip.Decode(new byte[7], 7, 1, 0x5A));
        Reject("truncated packed input", () => PackedRoundTrip.Decode(packed[..^1], packed.Length, plain.Length, 0x5A));
        Reject("extra packed input", () => PackedRoundTrip.Decode([..packed, 0], packed.Length, plain.Length, 0x5A));
        Reject("declared length", () => PackedRoundTrip.Decode(packed, packed.Length, plain.Length + 1, 0x5A));
        Reject("truncated stream at accepted file length", () => PackedRoundTrip.Decode(packed[..^1], packed.Length - 1, plain.Length, 0x5A));
        Reject("empty payload", () => PackedRoundTrip.Encode([], 0x5A));
        Reject("oversized payload", () => PackedRoundTrip.Encode(new byte[PackedRoundTrip.MaximumPayload + 1], 0x5A));
        Reject("zero pattern matches", () => PackedRoundTrip.Patch(plain, "1.2.3.4", 6001, "127.0.0.1", 6002, 1));
        Reject("wrong pattern count", () => PackedRoundTrip.Patch(plain, "52.63.34.162", 6001, "127.0.0.1", 6002, 2));
        Reject("extra pattern matches", () => PackedRoundTrip.Patch([..plain, ..plain], "52.63.34.162", 6001, "127.0.0.1", 6002, 1));
        Reject("unbounded pattern count", () => PackedRoundTrip.Patch(plain, "52.63.34.162", 6001, "127.0.0.1", 6002, 0));
        foreach (var ip in new[] { "localhost", "256.0.0.1", "127.1", "127.0.0.01", "127.0.0.1\r\n" })
            Reject("invalid IP", () => PackedRoundTrip.Patch(plain, "52.63.34.162", 6001, ip, 6002, 1));
        foreach (var port in new[] { -1, 0, 65536 })
            Reject("invalid port", () => PackedRoundTrip.Patch(plain, "52.63.34.162", 6001, "127.0.0.1", port, 1));
        Reject("invalid source endpoint", () => PackedRoundTrip.Patch(plain, "bad", 6001, "127.0.0.1", 6002, 1));
        var shortEndpoint = Encoding.ASCII.GetBytes(",1.1.1.1 asdf 6001\r\n");
        var fullPayload = Enumerable.Repeat((byte)'x', PackedRoundTrip.MaximumPayload).ToArray();
        shortEndpoint.CopyTo(fullPayload, 0);
        Reject("patched output exceeds limit", () => PackedRoundTrip.Patch(
            fullPayload, "1.1.1.1", 6001, "255.255.255.255", 65535, 1));
        var corrupt = packed.ToArray(); corrupt[8] ^= 1;
        Reject("output round-trip corruption", () => PackedRoundTrip.Verify(plain, corrupt, 0x5A));
        Console.WriteLine($"PASS: offline self-tests; {cases} fail-closed cases plus round-trip and exact patch checks.");
    }
}
