<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\God2.ClassicServer.Domain\God2.ClassicServer.Domain.csproj" />
    <ProjectReference Include="..\God2.ClassicServer.Application\God2.ClassicServer.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Evidence\OfficialProtocolCompletion\DecryptedPacketCorpus.20260807.v2.json" />
    <EmbeddedResource Include="Evidence\OfficialProtocolCompletion\God2Evidence.20260807.112752.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
