param([Parameter(Mandatory=$true)][int]$ProcessId,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop'
Add-Type -TypeDefinition @'
using System; using System.Runtime.InteropServices;
public static class WorldSubsystemNative {
 [DllImport("kernel32.dll",SetLastError=true)] public static extern IntPtr OpenProcess(uint a,bool i,int p);
 [DllImport("kernel32.dll",SetLastError=true)] public static extern bool ReadProcessMemory(IntPtr p,IntPtr a,byte[] b,IntPtr s,out IntPtr r);
 [DllImport("kernel32.dll")] public static extern bool CloseHandle(IntPtr h);
}
'@
function Read-Block([IntPtr]$h,[uint32]$a,[int]$n){$b=New-Object byte[] $n;$r=[IntPtr]::Zero;$ok=[WorldSubsystemNative]::ReadProcessMemory($h,[IntPtr]([int64]$a),$b,[IntPtr]$n,[ref]$r);$c=[int]$r.ToInt64();if($c-le0){return $null};if($c-lt$n){$z=New-Object byte[] $c;[Array]::Copy($b,$z,$c);return $z};$b}
$h=[WorldSubsystemNative]::OpenProcess(0x410,$false,$ProcessId);if($h-eq[IntPtr]::Zero){throw 'OpenProcess failed'}
try{$slot=Read-Block $h 0x008AD5F8 4;if(!$slot){throw 'handler slot unreadable'};$handler=[BitConverter]::ToUInt32($slot,0);$offsets=[ordered]@{Subsystem181C6BC=0x0181C6BC;Subsystem14BE014=0x014BE014;World1499FA0=0x01499FA0;Subsystem147C720=0x0147C720;Subsystem1464C58=0x01464C58};$reports=@();foreach($kv in $offsets.GetEnumerator()){$base=[uint32]($handler+[uint32]$kv.Value);$b=Read-Block $h $base 30464;if(!$b){$reports+=[pscustomobject]@{Name=$kv.Key;Base=('0x{0:X8}'-f$base);Readable=$false};continue};$sentinels=0;$plausible=@();for($i=0x70;$i+0x1D8-le$b.Length-and$i-lt(0x70+64*0x1D8);$i+=0x1D8){$id=[BitConverter]::ToUInt32($b,$i);if($id-eq[uint32]::MaxValue){$sentinels++;continue};$x=[BitConverter]::ToInt32($b,$i+0x10);$y=[BitConverter]::ToInt32($b,$i+0x14);$rx=[BitConverter]::ToInt32($b,$i+0x180);$ry=[BitConverter]::ToInt32($b,$i+0x184);if($id-lt10000000-and$x-ge0-and$x-lt4096-and$y-ge0-and$y-lt4096){$plausible+=[pscustomobject]@{Slot=(($i-0x70)/0x1D8);ObjectId=$id;X=$x;Y=$y;RuntimeX=$rx;RuntimeY=$ry;Field04=[BitConverter]::ToUInt16($b,$i+4);Field06=[BitConverter]::ToUInt16($b,$i+6);Field0A=[BitConverter]::ToUInt16($b,$i+0x0A)}}};$reports+=[pscustomobject]@{Name=$kv.Key;Base=('0x{0:X8}'-f$base);Readable=$true;BytesRead=$b.Length;VTable=('0x{0:X8}'-f[BitConverter]::ToUInt32($b,0));SentinelSlots=$sentinels;PlausibleEntityCount=@($plausible).Count;PlausibleEntities=$plausible;HexPrefix=([BitConverter]::ToString($b,0,[Math]::Min(256,$b.Length))).Replace('-','')}};$result=[ordered]@{SchemaVersion='god2-live-world-subsystems-v1';CapturedAt=[DateTimeOffset]::Now.ToString('o');ProcessId=$ProcessId;Handler=('0x{0:X8}'-f$handler);Subsystems=$reports};$result|ConvertTo-Json -Depth 7|Set-Content -LiteralPath $OutputPath -Encoding UTF8;$result|ConvertTo-Json -Depth 7}finally{[void][WorldSubsystemNative]::CloseHandle($h)}
