<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\God2.ServerV2.Core\God2.ServerV2.Core.csproj" />
    <ProjectReference Include="..\God2.ServerV2.Network\God2.ServerV2.Network.csproj" />
    <ProjectReference Include="..\God2.ServerV2.Session\God2.ServerV2.Session.csproj" />
  </ItemGroup>
</Project>
