CREATE TABLE IF NOT EXISTS `monster_combat_runtime_state` (
    `RuntimeEntityId` bigint NOT NULL,
    `MonsterTemplateId` int NOT NULL,
    `SpawnDefinitionId` int NOT NULL,
    `SpawnGroupId` varchar(128) NOT NULL,
    `WorldInstanceId` varchar(128) NOT NULL,
    `MapId` int NOT NULL,
    `PositionX` int NOT NULL,
    `PositionY` int NOT NULL,
    `PositionZ` int NOT NULL,
    `Direction` varchar(32) NOT NULL,
    `LifecycleState` varchar(32) NOT NULL,
    `CombatState` varchar(32) NOT NULL,
    `Level` int NOT NULL,
    `MaximumHp` bigint NOT NULL,
    `CurrentHp` bigint NOT NULL,
    `AttackPower` bigint NOT NULL,
    `Defense` bigint NOT NULL,
    `Accuracy` bigint NULL,
    `Evasion` bigint NULL,
    `AttackIntervalPolicy` varchar(64) NOT NULL,
    `AggroState` varchar(64) NOT NULL,
    `CurrentTargetRuntimeEntityId` bigint NULL,
    `RuntimeVersion` bigint NOT NULL,
    `DirtyFlags` varchar(256) NOT NULL,
    `SpawnedAtUtc` datetime(6) NOT NULL,
    `LastCombatAtUtc` datetime(6) NULL,
    `DiedAtUtc` datetime(6) NULL,
    `RespawnDueAtUtc` datetime(6) NULL,
    `StatPolicyStatus` varchar(32) NOT NULL,
    `ContentVersion` varchar(128) NOT NULL,
    `RawMetadata` longtext NOT NULL,
    `UpdatedAtUtc` datetime(6) NOT NULL,
    PRIMARY KEY (`RuntimeEntityId`),
    KEY `IX_MonsterCombatRuntime_Spawn` (`SpawnDefinitionId`, `RuntimeVersion`),
    KEY `IX_MonsterCombatRuntime_State` (`MapId`, `LifecycleState`, `CombatState`),
    CONSTRAINT `CK_MonsterCombatRuntime_Hp`
        CHECK (`MaximumHp` > 0 AND `CurrentHp` >= 0 AND `CurrentHp` <= `MaximumHp`),
    CONSTRAINT `CK_MonsterCombatRuntime_Stats`
        CHECK (`Level` >= 0 AND `AttackPower` >= 0 AND `Defense` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `combat_idempotency` (
    `IdempotencyKeyHash` char(64) NOT NULL,
    `CombatIntentId` char(36) NOT NULL,
    `CharacterId` bigint NOT NULL,
    `PayloadHash` char(64) NOT NULL,
    `ResultJson` longtext NOT NULL,
    `PendingRewardPlanJson` longtext NULL,
    `CreatedAtUtc` datetime(6) NOT NULL,
    `CompletedAtUtc` datetime(6) NOT NULL,
    PRIMARY KEY (`IdempotencyKeyHash`),
    UNIQUE KEY `UX_CombatIdempotency_Intent` (`CombatIntentId`),
    KEY `IX_CombatIdempotency_Character` (`CharacterId`, `CompletedAtUtc`),
    CONSTRAINT `FK_CombatIdempotency_Character`
        FOREIGN KEY (`CharacterId`) REFERENCES `characters` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `monster_death_records` (
    `DeathId` char(36) NOT NULL,
    `CombatIntentId` char(36) NOT NULL,
    `MonsterRuntimeEntityId` bigint NOT NULL,
    `MonsterTemplateId` int NOT NULL,
    `KillerRuntimeEntityId` bigint NOT NULL,
    `KillerCharacterId` bigint NOT NULL,
    `MapId` int NOT NULL,
    `SpawnDefinitionId` int NOT NULL,
    `HpBefore` bigint NOT NULL,
    `FinalDamage` bigint NOT NULL,
    `DiedAtUtc` datetime(6) NOT NULL,
    `RewardPolicyStatus` varchar(32) NOT NULL,
    `DropPolicyStatus` varchar(32) NOT NULL,
    `RespawnPolicyStatus` varchar(32) NOT NULL,
    `RuntimeVersionBefore` bigint NOT NULL,
    `RuntimeVersionAfter` bigint NOT NULL,
    `CorrelationId` varchar(128) NOT NULL,
    PRIMARY KEY (`DeathId`),
    UNIQUE KEY `UX_MonsterDeath_CombatIntent` (`CombatIntentId`),
    KEY `IX_MonsterDeath_Spawn` (`SpawnDefinitionId`, `DiedAtUtc`),
    CONSTRAINT `FK_MonsterDeath_Character`
        FOREIGN KEY (`KillerCharacterId`) REFERENCES `characters` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `monster_respawn_schedules` (
    `RespawnId` char(36) NOT NULL,
    `DeathId` char(36) NOT NULL,
    `MonsterTemplateId` int NOT NULL,
    `SpawnDefinitionId` int NOT NULL,
    `SpawnGroupId` varchar(128) NOT NULL,
    `WorldInstanceId` varchar(128) NOT NULL,
    `MapId` int NOT NULL,
    `PositionX` int NOT NULL,
    `PositionY` int NOT NULL,
    `PositionZ` int NOT NULL,
    `Direction` varchar(32) NOT NULL,
    `RespawnDueAtUtc` datetime(6) NOT NULL,
    `PolicyStatus` varchar(32) NOT NULL,
    `State` varchar(32) NOT NULL,
    `CreatedAtUtc` datetime(6) NOT NULL,
    `CorrelationId` varchar(128) NOT NULL,
    `PreviousRuntimeEntityId` bigint NOT NULL,
    `NewRuntimeEntityId` bigint NULL,
    `FailureCode` varchar(128) NOT NULL DEFAULT '',
    `CompletedAtUtc` datetime(6) NULL,
    PRIMARY KEY (`RespawnId`),
    UNIQUE KEY `UX_MonsterRespawn_Death` (`DeathId`),
    KEY `IX_MonsterRespawn_Due` (`State`, `RespawnDueAtUtc`),
    CONSTRAINT `FK_MonsterRespawn_Death`
        FOREIGN KEY (`DeathId`) REFERENCES `monster_death_records` (`DeathId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `combat_audit` (
    `AuditId` char(36) NOT NULL,
    `CombatIntentId` char(36) NOT NULL,
    `DamagePlanId` char(36) NULL,
    `DeathId` char(36) NULL,
    `RewardPlanId` char(36) NULL,
    `RespawnId` char(36) NULL,
    `IdempotencySafeId` varchar(32) NOT NULL,
    `CorrelationId` varchar(128) NOT NULL,
    `SessionId` varchar(128) NOT NULL,
    `CharacterId` bigint NOT NULL,
    `AttackerRuntimeEntityId` bigint NOT NULL,
    `TargetRuntimeEntityId` bigint NOT NULL,
    `AttackerTemplateId` int NOT NULL,
    `TargetTemplateId` int NOT NULL,
    `ActionType` varchar(32) NOT NULL,
    `MapId` int NOT NULL,
    `AttackerVersionBefore` bigint NOT NULL,
    `AttackerVersionAfter` bigint NOT NULL,
    `TargetVersionBefore` bigint NOT NULL,
    `TargetVersionAfter` bigint NOT NULL,
    `HpBefore` bigint NOT NULL,
    `Damage` bigint NOT NULL,
    `HpAfter` bigint NOT NULL,
    `Result` varchar(64) NOT NULL,
    `FailureCode` varchar(128) NOT NULL,
    `DeathCommitted` tinyint(1) NOT NULL,
    `RewardCommitted` tinyint(1) NOT NULL,
    `RespawnScheduled` tinyint(1) NOT NULL,
    `PolicyStatus` varchar(32) NOT NULL,
    `CreatedAtUtc` datetime(6) NOT NULL,
    `CompletedAtUtc` datetime(6) NOT NULL,
    PRIMARY KEY (`AuditId`),
    KEY `IX_CombatAudit_Character` (`CharacterId`, `CompletedAtUtc`),
    KEY `IX_CombatAudit_Target` (`TargetRuntimeEntityId`, `CompletedAtUtc`),
    KEY `IX_CombatAudit_Intent` (`CombatIntentId`),
    CONSTRAINT `FK_CombatAudit_Character`
        FOREIGN KEY (`CharacterId`) REFERENCES `characters` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
