CREATE TABLE IF NOT EXISTS `god2_game`.`client_map_resources` (
    `resource_key` varchar(512) NOT NULL COMMENT '客戶端地圖資源權威鍵',
    `area_code` varchar(64) NOT NULL COMMENT 'CAN 區域代碼',
    `resource_name` varchar(256) NOT NULL COMMENT 'CAN 內地圖資源名稱',
    `can_record_index` int NOT NULL COMMENT 'CAN 記錄索引',
    `can_record_type` tinyint unsigned NOT NULL COMMENT 'CAN 記錄類型原始值',
    `grid_width` int NULL COMMENT 'MBD 網格寬度；未知時為 NULL',
    `grid_height` int NULL COMMENT 'MBD 網格高度；未知時為 NULL',
    `minimum_x` int NULL COMMENT '推導的最小世界 X 座標',
    `maximum_x` int NULL COMMENT '依每格 21 單位推導的最大世界 X 座標',
    `minimum_y` int NULL COMMENT '推導的最小世界 Y 座標',
    `maximum_y` int NULL COMMENT '依每格 21 單位推導的最大世界 Y 座標',
    `canonical_map_id` bigint NULL COMMENT '已驗證的正式地圖 ID；未綁定時為 NULL',
    `client_build_id` varchar(64) NOT NULL COMMENT '客戶端版本 ID',
    `client_executable_sha256` char(64) NOT NULL COMMENT '客戶端執行檔 SHA-256',
    `client_map_id` int NULL COMMENT '已驗證的 Client Map ID',
    `client_area_id` int NULL COMMENT '已驗證的 Client Area ID',
    `can_relative_path` varchar(512) NOT NULL COMMENT 'CAN 相對路徑',
    `can_sha256` char(64) NOT NULL COMMENT 'CAN 檔案 SHA-256',
    `mbd_relative_path` varchar(512) NULL COMMENT 'MBD 或 MBDZ 相對路徑',
    `mbd_sha256` char(64) NULL COMMENT 'MBD 或 MBDZ 檔案 SHA-256',
    `resource_evidence_status` varchar(30) NOT NULL DEFAULT 'Derived' COMMENT '資源結構證據狀態',
    `map_identity_evidence_status` varchar(30) NOT NULL DEFAULT 'Unknown' COMMENT '數字地圖識別證據狀態',
    `portal_placement_evidence_status` varchar(30) NOT NULL DEFAULT 'Unknown' COMMENT '傳送點配置證據狀態',
    `enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否可進入正式 Runtime',
    `admin_note` varchar(500) NULL COMMENT '服主管理備註',
    `created_at_utc` datetime(6) NOT NULL DEFAULT UTC_TIMESTAMP(6) COMMENT '建立 UTC 時間',
    `updated_at_utc` datetime(6) NOT NULL DEFAULT UTC_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新 UTC 時間',
    PRIMARY KEY (`resource_key`),
    UNIQUE KEY `ux_client_map_resources_can_record` (`client_build_id`,`can_sha256`,`can_record_index`),
    KEY `ix_client_map_resources_area` (`area_code`,`resource_name`),
    KEY `ix_client_map_resources_canonical_map` (`canonical_map_id`),
    KEY `ix_client_map_resources_client_map` (`client_build_id`,`client_map_id`,`client_area_id`),
    KEY `ix_client_map_resources_enabled` (`enabled`),
    CONSTRAINT `fk_client_map_resources_canonical_map` FOREIGN KEY (`canonical_map_id`) REFERENCES `god2_game`.`maps` (`map_id`),
    CONSTRAINT `ck_client_map_resources_enabled` CHECK (`enabled` IN (0,1)),
    CONSTRAINT `ck_client_map_resources_grid` CHECK ((`grid_width` IS NULL AND `grid_height` IS NULL) OR (`grid_width`>0 AND `grid_height`>0)),
    CONSTRAINT `ck_client_map_resources_gate` CHECK (`enabled`=0 OR (`canonical_map_id` IS NOT NULL AND `client_map_id` IS NOT NULL AND `client_area_id` IS NOT NULL AND `map_identity_evidence_status` IN ('Verified','Derived')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶端完整地圖資源清冊；與正式地圖及傳送點分離';
