CREATE OR REPLACE VIEW `god2_game`.`vw_pet_templates_readable` AS
SELECT template_row.`pet_template_id` AS `戰寵模板ID`,
       template_row.`name_zh_tw` AS `戰寵名稱`,
       template_row.`pet_family` AS `戰寵族系`,
       category_row.`name_zh_tw` AS `戰寵族群`,
       template_row.`element_zh_tw` AS `五行`,
       template_row.`base_level` AS `玩家初始等級`,
       monster_row.`name_zh_tw` AS `野生怪物來源`,
       monster_row.`level` AS `野生遭遇等級`,
       COALESCE(NULLIF(template_row.`level_20_skill_name_zh_tw`, ''), '未配置') AS `20級技能`,
       COALESCE(NULLIF(template_row.`level_40_skill_name_zh_tw`, ''), '未配置') AS `40級技能`,
       COALESCE(NULLIF(template_row.`level_60_skill_name_zh_tw`, ''), '未配置') AS `60級技能`,
       template_row.`capture_rule_zh_tw` AS `捕捉轉換規則`,
       template_row.`base_max_hp` AS `基礎最大HP`,
       template_row.`base_max_mp` AS `基礎最大MP`,
       template_row.`base_strength` AS `基礎力量`,
       template_row.`base_constitution` AS `基礎體力`,
       template_row.`base_intelligence` AS `基礎智力`,
       template_row.`base_speed` AS `基礎速度`,
       template_row.`maximum_skill_slots` AS `最大技能格`,
       CASE WHEN template_row.`enabled` = 1 THEN '已啟用' ELSE '未啟用' END AS `正式狀態`
FROM `god2_game`.`pet_templates` template_row
LEFT JOIN `god2_game`.`pet_categories` category_row ON category_row.`category_id` = template_row.`pet_category_id`
LEFT JOIN `god2_game`.`monsters` monster_row ON monster_row.`monster_id` = template_row.`wild_source_monster_id`;

CREATE OR REPLACE VIEW `god2_game`.`vw_pet_templates_full` AS
SELECT template_row.`pet_template_id` AS `戰寵模板ID`,
       template_row.`code` AS `代碼`,
       template_row.`name_zh_tw` AS `名稱`,
       template_row.`pet_family` AS `戰寵族系`,
       template_row.`pet_category_id` AS `戰寵族群ID`,
       template_row.`wild_source_monster_id` AS `野生怪物來源ID`,
       template_row.`element_zh_tw` AS `五行`,
       template_row.`base_level` AS `基礎等級`,
       template_row.`base_max_hp` AS `基礎最大HP`,
       template_row.`base_max_mp` AS `基礎最大MP`,
       template_row.`base_max_lifespan` AS `基礎最大壽命`,
       template_row.`base_strength` AS `力量`,
       template_row.`base_constitution` AS `體力`,
       template_row.`base_intelligence` AS `智力`,
       template_row.`base_speed` AS `速度`,
       template_row.`base_metal` AS `金`,
       template_row.`base_wood` AS `木`,
       template_row.`base_water` AS `水`,
       template_row.`base_fire` AS `火`,
       template_row.`base_earth` AS `土`,
       template_row.`base_physical_attack` AS `物攻`,
       template_row.`base_physical_defense` AS `物防`,
       template_row.`base_magic_attack` AS `魔攻`,
       template_row.`base_magic_defense` AS `魔防`,
       template_row.`initial_stat_points` AS `初始配點`,
       template_row.`maximum_skill_slots` AS `最大技能格`,
       COALESCE(NULLIF(template_row.`level_20_skill_name_zh_tw`, ''), '未配置') AS `20級技能`,
       COALESCE(NULLIF(template_row.`level_40_skill_name_zh_tw`, ''), '未配置') AS `40級技能`,
       COALESCE(NULLIF(template_row.`level_60_skill_name_zh_tw`, ''), '未配置') AS `60級技能`,
       template_row.`capture_rule_zh_tw` AS `捕捉轉換規則`,
       CASE WHEN template_row.`enabled` = 1 THEN '已啟用' ELSE '未啟用' END AS `正式狀態`
FROM `god2_game`.`pet_templates` template_row;
