ALTER TABLE `god2_game`.`public_beta_skill_effect_v0`
  MODIFY COLUMN `global_record_id` int(11) NOT NULL COMMENT '公測技能效果全域記錄 ID',
  MODIFY COLUMN `record_id_in_bank` int(11) NOT NULL COMMENT '同一技能資料分組內的記錄 ID',
  MODIFY COLUMN `bank` int(11) NOT NULL COMMENT '技能資料分組編號',
  MODIFY COLUMN `slot_one_based` int(11) NOT NULL COMMENT '技能格序號；從 1 起算',
  MODIFY COLUMN `name_zh_tw` varchar(256) NULL COMMENT '技能繁體中文名稱；未知時為 NULL',
  MODIFY COLUMN `description_zh_tw` varchar(500) NULL COMMENT '技能繁體中文說明；未知時為 NULL',
  MODIFY COLUMN `skill_level` int(11) NULL COMMENT '技能階級或等級；未知時為 NULL',
  MODIFY COLUMN `implementation_family` varchar(64) NOT NULL COMMENT '服務端功能族群',
  MODIFY COLUMN `effect_kind` varchar(32) NOT NULL COMMENT '技能效果種類',
  MODIFY COLUMN `status_or_axis` varchar(64) NULL COMMENT '狀態效果或能力軸；不適用時為 NULL',
  MODIFY COLUMN `mp_cost` int(11) NULL COMMENT '技能 MP 消耗；未知時為 NULL',
  MODIFY COLUMN `target_context` int(11) NULL COMMENT '客戶端目標情境代碼；未知時為 NULL',
  MODIFY COLUMN `target_scope` int(11) NULL COMMENT '客戶端目標範圍代碼；未知時為 NULL',
  MODIFY COLUMN `numeric_effect_fields` varchar(1000) NULL COMMENT '已整理的數值效果欄位摘要；未知時為 NULL',
  MODIFY COLUMN `v0_to_v23_nonzero` varchar(1500) NULL COMMENT '公測效果欄位中非零數值摘要；供比對服務端規則',
  MODIFY COLUMN `minimum_working_server_rule` varchar(1500) NOT NULL COMMENT '目前可套用的最低服務端規則',
  MODIFY COLUMN `provisional_success_rule` varchar(500) NULL COMMENT '暫定成功率規則；尚無證據時為 NULL',
  MODIFY COLUMN `provisional_duration_rule` varchar(500) NULL COMMENT '暫定持續時間規則；尚無證據時為 NULL',
  MODIFY COLUMN `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否納入技能效果候選目錄',
  MODIFY COLUMN `created_at_utc` datetime(6) NOT NULL DEFAULT utc_timestamp(6) COMMENT '建立時間（UTC）',
  MODIFY COLUMN `updated_at_utc` datetime(6) NOT NULL DEFAULT utc_timestamp(6) ON UPDATE current_timestamp(6) COMMENT '更新時間（UTC）';
