-- Schema 361
-- Game function: formal database text quality audit for player-visible and server-written Traditional Chinese fields.
-- Purpose: keep mojibake, Simplified-only notes, and unreadable text out of the formal server database.

CREATE OR REPLACE VIEW `god2_game`.`vw_formal_text_quality_mojibake_audit_readable` AS
SELECT 'god2_game.item_registry' AS `資料表`,
       'name_zh_tw' AS `欄位`,
       COUNT(*) AS `可疑筆數`,
       CASE WHEN COUNT(*)=0 THEN '通過' ELSE '需要清理' END AS `狀態`
FROM `god2_game`.`item_registry`
WHERE `name_zh_tw` LIKE '%鎻愬%'
   OR `name_zh_tw` LIKE '%瑙ｉ%'
   OR `name_zh_tw` LIKE '%瀹㈡%'
   OR `name_zh_tw` LIKE '%鏁堟%'
   OR `name_zh_tw` LIKE '%鐢熷%'
   OR `name_zh_tw` LIKE '%娉曞%'
   OR `name_zh_tw` LIKE '%鎭㈠%'
   OR `name_zh_tw` LIKE '%涓%'
   OR `name_zh_tw` LIKE '%绁炰%'
   OR `name_zh_tw` LIKE '%娣蜂%'
   OR `name_zh_tw` LIKE '%閬撳%'
   OR `name_zh_tw` LIKE '%鐙€%'
   OR `name_zh_tw` LIKE '%鍟熺%'
   OR `name_zh_tw` LIKE '%浣跨%'
   OR `name_zh_tw` LIKE '%鐗╁%'
   OR `name_zh_tw` LIKE '%鎴愬%'
   OR `name_zh_tw` LIKE '%锛%'
   OR `name_zh_tw` LIKE '%简体%'
UNION ALL
SELECT 'god2_game.item_registry','description_zh_tw',COUNT(*),CASE WHEN COUNT(*)=0 THEN '通過' ELSE '需要清理' END
FROM `god2_game`.`item_registry`
WHERE `description_zh_tw` LIKE '%鎻愬%'
   OR `description_zh_tw` LIKE '%瑙ｉ%'
   OR `description_zh_tw` LIKE '%瀹㈡%'
   OR `description_zh_tw` LIKE '%鏁堟%'
   OR `description_zh_tw` LIKE '%鐢熷%'
   OR `description_zh_tw` LIKE '%娉曞%'
   OR `description_zh_tw` LIKE '%鎭㈠%'
   OR `description_zh_tw` LIKE '%涓%'
   OR `description_zh_tw` LIKE '%绁炰%'
   OR `description_zh_tw` LIKE '%娣蜂%'
   OR `description_zh_tw` LIKE '%閬撳%'
   OR `description_zh_tw` LIKE '%鐙€%'
   OR `description_zh_tw` LIKE '%鍟熺%'
   OR `description_zh_tw` LIKE '%浣跨%'
   OR `description_zh_tw` LIKE '%鐗╁%'
   OR `description_zh_tw` LIKE '%鎴愬%'
   OR `description_zh_tw` LIKE '%锛%'
   OR `description_zh_tw` LIKE '%简体%'
UNION ALL
SELECT 'god2_game.item_effects','effect_type',COUNT(*),CASE WHEN COUNT(*)=0 THEN '通過' ELSE '需要清理' END
FROM `god2_game`.`item_effects`
WHERE `effect_type` LIKE '%鎻愬%'
   OR `effect_type` LIKE '%瑙ｉ%'
   OR `effect_type` LIKE '%瀹㈡%'
   OR `effect_type` LIKE '%鏁堟%'
   OR `effect_type` LIKE '%鐢熷%'
   OR `effect_type` LIKE '%娉曞%'
   OR `effect_type` LIKE '%鎭㈠%'
   OR `effect_type` LIKE '%涓%'
   OR `effect_type` LIKE '%绁炰%'
   OR `effect_type` LIKE '%娣蜂%'
   OR `effect_type` LIKE '%閬撳%'
   OR `effect_type` LIKE '%鐙€%'
   OR `effect_type` LIKE '%鍟熺%'
   OR `effect_type` LIKE '%浣跨%'
   OR `effect_type` LIKE '%鐗╁%'
   OR `effect_type` LIKE '%鎴愬%'
   OR `effect_type` LIKE '%锛%'
   OR `effect_type` LIKE '%简体%'
UNION ALL
SELECT 'god2_game.item_effects','effect_text_zh_tw',COUNT(*),CASE WHEN COUNT(*)=0 THEN '通過' ELSE '需要清理' END
FROM `god2_game`.`item_effects`
WHERE `effect_text_zh_tw` LIKE '%鎻愬%'
   OR `effect_text_zh_tw` LIKE '%瑙ｉ%'
   OR `effect_text_zh_tw` LIKE '%瀹㈡%'
   OR `effect_text_zh_tw` LIKE '%鏁堟%'
   OR `effect_text_zh_tw` LIKE '%鐢熷%'
   OR `effect_text_zh_tw` LIKE '%娉曞%'
   OR `effect_text_zh_tw` LIKE '%鎭㈠%'
   OR `effect_text_zh_tw` LIKE '%涓%'
   OR `effect_text_zh_tw` LIKE '%绁炰%'
   OR `effect_text_zh_tw` LIKE '%娣蜂%'
   OR `effect_text_zh_tw` LIKE '%閬撳%'
   OR `effect_text_zh_tw` LIKE '%鐙€%'
   OR `effect_text_zh_tw` LIKE '%鍟熺%'
   OR `effect_text_zh_tw` LIKE '%浣跨%'
   OR `effect_text_zh_tw` LIKE '%鐗╁%'
   OR `effect_text_zh_tw` LIKE '%鎴愬%'
   OR `effect_text_zh_tw` LIKE '%锛%'
   OR `effect_text_zh_tw` LIKE '%简体%'
UNION ALL
SELECT 'god2.status_effects','Name',COUNT(*),CASE WHEN COUNT(*)=0 THEN '通過' ELSE '需要清理' END
FROM `god2`.`status_effects`
WHERE `Name` LIKE '%鎻愬%'
   OR `Name` LIKE '%瑙ｉ%'
   OR `Name` LIKE '%瀹㈡%'
   OR `Name` LIKE '%鏁堟%'
   OR `Name` LIKE '%鐢熷%'
   OR `Name` LIKE '%娉曞%'
   OR `Name` LIKE '%鎭㈠%'
   OR `Name` LIKE '%涓%'
   OR `Name` LIKE '%绁炰%'
   OR `Name` LIKE '%娣蜂%'
   OR `Name` LIKE '%閬撳%'
   OR `Name` LIKE '%鐙€%'
   OR `Name` LIKE '%鍟熺%'
   OR `Name` LIKE '%浣跨%'
   OR `Name` LIKE '%鐗╁%'
   OR `Name` LIKE '%鎴愬%'
   OR `Name` LIKE '%锛%'
   OR `Name` LIKE '%简体%'
UNION ALL
SELECT 'god2_player.inventory_audit_ledger','OperationType/Source/CurrencyType/Result',COUNT(*),CASE WHEN COUNT(*)=0 THEN '通過' ELSE '需要清理' END
FROM `god2_player`.`inventory_audit_ledger`
WHERE `OperationType` LIKE '%鎻愬%'
   OR `OperationType` LIKE '%瑙ｉ%'
   OR `OperationType` LIKE '%瀹㈡%'
   OR `OperationType` LIKE '%鏁堟%'
   OR `OperationType` LIKE '%鐢熷%'
   OR `OperationType` LIKE '%娉曞%'
   OR `OperationType` LIKE '%鎭㈠%'
   OR `OperationType` LIKE '%涓%'
   OR `OperationType` LIKE '%绁炰%'
   OR `OperationType` LIKE '%娣蜂%'
   OR `OperationType` LIKE '%锛%'
   OR `Source` LIKE '%鎻愬%'
   OR `Source` LIKE '%瑙ｉ%'
   OR `Source` LIKE '%瀹㈡%'
   OR `Source` LIKE '%鏁堟%'
   OR `Source` LIKE '%鐢熷%'
   OR `Source` LIKE '%娉曞%'
   OR `Source` LIKE '%鎭㈠%'
   OR `Source` LIKE '%涓%'
   OR `Source` LIKE '%绁炰%'
   OR `Source` LIKE '%娣蜂%'
   OR `Source` LIKE '%锛%'
   OR `CurrencyType` LIKE '%锛%'
   OR `Result` LIKE '%锛%';
