-- Migration 434: intake XJZ client-recovered monster skill probe targets.
-- Function: monster battle skill evidence worklist. This does not promote runtime monster skills
-- because the client evidence identifies which monsters must be probed, not skill ids/probability.

CREATE TABLE IF NOT EXISTS god2_research.xjz_monster_skill_probe_targets (
  probe_id BIGINT NOT NULL COMMENT 'XJZ 怪物技能抓包目標 ID',
  monster_code INT NOT NULL COMMENT '客戶端怪物代碼',
  monster_name_zh_tw VARCHAR(150) NOT NULL COMMENT '怪物名稱（繁體中文）',
  field_rom_path VARCHAR(255) NULL COMMENT '場景怪物 ROM 路徑',
  battle_rom_path VARCHAR(255) NULL COMMENT '戰鬥怪物 ROM 路徑',
  actor_skill_kind VARCHAR(64) NOT NULL COMMENT '技能施放者類型',
  wanted_fields_zh_tw VARCHAR(255) NOT NULL COMMENT '需要補證的欄位',
  capture_target_table VARCHAR(100) NOT NULL COMMENT '建議抓包回填表',
  source_file VARCHAR(500) NOT NULL COMMENT '證據來源檔案',
  source_line INT NULL COMMENT '證據來源行號',
  evidence_status_zh_tw VARCHAR(100) NOT NULL COMMENT '目前證據狀態',
  needs_packet_evidence TINYINT(1) NOT NULL COMMENT '是否仍需要封包或黑箱證據',
  formal_monster_id BIGINT NULL COMMENT '正式服務端怪物 ID',
  formal_monster_name_zh_tw VARCHAR(150) NULL COMMENT '正式服務端怪物名稱',
  formal_link_status_zh_tw VARCHAR(80) NOT NULL DEFAULT '待連結' COMMENT '正式怪物連結狀態',
  created_at_utc DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6) COMMENT '建立 UTC 時間',
  PRIMARY KEY (probe_id),
  UNIQUE KEY ux_xjz_monster_skill_probe_monster_code (monster_code),
  KEY ix_xjz_monster_skill_probe_formal_monster (formal_monster_id),
  KEY ix_xjz_monster_skill_probe_needed (needs_packet_evidence),
  CONSTRAINT ck_xjz_monster_skill_probe_needs_packet CHECK (needs_packet_evidence IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='XJZ 客戶端還原怪物技能抓包目標';

TRUNCATE TABLE god2_research.xjz_monster_skill_probe_targets;

INSERT INTO god2_research.xjz_monster_skill_probe_targets
  (probe_id, monster_code, monster_name_zh_tw, field_rom_path, battle_rom_path, actor_skill_kind,
   wanted_fields_zh_tw, capture_target_table, source_file, source_line, evidence_status_zh_tw, needs_packet_evidence)
VALUES
(1,1,'海柱','data2\rom\eny\eny3001.ROM','data2\fight\eny\eny5001.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',5,'客戶端怪物外觀身份定位',1),
(2,2,'麵包蕈','data2\rom\eny\eny3002.ROM','data2\fight\eny\eny5002.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',6,'客戶端怪物外觀身份定位',1),
(3,3,'魔眼','data2\rom\eny\eny3003.ROM','data2\fight\eny\eny5003.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',7,'客戶端怪物外觀身份定位',1),
(4,4,'土蟲','data2\rom\eny\eny3004.ROM','data2\fight\eny\eny5004.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',8,'客戶端怪物外觀身份定位',1),
(5,5,'鬼火','data2\rom\eny\eny3005.ROM','data2\fight\eny\eny5005.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',9,'客戶端怪物外觀身份定位',1),
(6,6,'怨靈','data2\rom\eny\eny3006.ROM','data2\fight\eny\eny5006.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',10,'客戶端怪物外觀身份定位',1),
(7,7,'氐獸','data2\rom\eny\eny3007.ROM','data2\fight\eny\eny5007.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',11,'客戶端怪物外觀身份定位',1),
(8,8,'樹靈','data2\rom\eny\eny3008.ROM','data2\fight\eny\eny5008.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',12,'客戶端怪物外觀身份定位',1),
(9,9,'海童','data2\rom\eny\eny3009.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',13,'客戶端怪物外觀身份定位',1),
(10,10,'迷蹤獸','data2\rom\eny\eny3010.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',14,'客戶端怪物外觀身份定位',1),
(11,11,'鳳鳥','data2\rom\eny\eny3011.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',15,'客戶端怪物外觀身份定位',1),
(12,12,'血吞','data2\rom\eny\eny3012.ROM','data2\fight\eny\eny5012.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',16,'客戶端怪物外觀身份定位',1),
(13,13,'食屍鳥','data2\rom\eny\eny3013.ROM','data2\fight\eny\eny5013.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',17,'客戶端怪物外觀身份定位',1),
(14,14,'白眉','data2\rom\eny\eny3014.ROM','data2\fight\eny\eny5014.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',18,'客戶端怪物外觀身份定位',1),
(15,15,'鴛鴨','data2\rom\eny\eny3015.ROM','data2\fight\eny\eny5015.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',19,'客戶端怪物外觀身份定位',1),
(16,16,'白骨','data2\rom\eny\eny3016.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',20,'客戶端怪物外觀身份定位',1),
(17,17,'山魅','data2\rom\eny\eny3017.ROM','data2\fight\eny\eny5017.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',21,'客戶端怪物外觀身份定位',1),
(18,18,'赤鬼','data2\rom\eny\eny3018.ROM','data2\fight\eny\eny5018.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',22,'客戶端怪物外觀身份定位',1),
(19,19,'魔獸','data2\rom\eny\eny3019.ROM','data2\fight\eny\eny5019.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',23,'客戶端怪物外觀身份定位',1),
(20,20,'巨靈','data2\rom\eny\eny3020.ROM','data2\fight\eny\eny5020.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',24,'客戶端怪物外觀身份定位',1),
(21,21,'森林矮人','data2\rom\eny\eny3021.ROM','data2\fight\eny\eny5021.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',25,'客戶端怪物外觀身份定位',1),
(22,22,'三眼','data2\rom\eny\eny3022.ROM','data2\fight\eny\eny5022.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',26,'客戶端怪物外觀身份定位',1),
(23,23,'吼獸','data2\rom\eny\eny3023.ROM','data2\fight\eny\eny5023.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',27,'客戶端怪物外觀身份定位',1),
(24,24,'寒獸','data2\rom\eny\eny3024.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',28,'客戶端怪物外觀身份定位',1),
(25,25,'闊嘴虎','data2\rom\eny\eny3025.ROM','data2\fight\eny\eny5025.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',29,'客戶端怪物外觀身份定位',1),
(26,26,'哮天犬','data2\rom\eny\eny3026.ROM','data2\fight\eny\eny5026.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',30,'客戶端怪物外觀身份定位',1),
(27,27,'鬼狐','data2\rom\eny\eny3027.ROM','data2\fight\eny\eny5027.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',31,'客戶端怪物外觀身份定位',1),
(28,28,'土怪','data2\rom\eny\eny3028.ROM','data2\fight\eny\eny5028.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',32,'客戶端怪物外觀身份定位',1),
(29,29,'覆地鼠','data2\rom\eny\eny3029.ROM','data2\fight\eny\eny5029.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',33,'客戶端怪物外觀身份定位',1),
(30,30,'野兔','data2\rom\eny\eny3030.ROM','data2\fight\eny\eny5030.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',34,'客戶端怪物外觀身份定位',1),
(31,31,'硬棘龍','data2\rom\eny\eny3031.ROM','data2\fight\eny\eny5031.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',35,'客戶端怪物外觀身份定位',1),
(32,32,'靈足','data2\rom\eny\eny3032.ROM','data2\fight\eny\eny5032.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',36,'客戶端怪物外觀身份定位',1),
(33,33,'寒離','data2\rom\eny\eny3033.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',37,'客戶端繁中文字串定位',1),
(34,34,'冥鬼','data2\rom\eny\eny3034.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',38,'客戶端怪物外觀身份定位',1),
(35,35,'巨翅蟲','data2\rom\eny\eny3035.ROM','data2\fight\eny\eny5035.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',39,'客戶端怪物外觀身份定位',1),
(36,36,'粉蠅','data2\rom\eny\eny3036.ROM','data2\fight\eny\eny5036.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',40,'客戶端怪物外觀身份定位',1),
(37,37,'巨翔蟲','data2\rom\eny\eny3037.ROM','data2\fight\eny\eny5037.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',41,'客戶端怪物外觀身份定位',1),
(38,38,'盾蟲','data2\rom\eny\eny3038.ROM','data2\fight\eny\eny5038.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',42,'客戶端怪物外觀身份定位',1),
(39,39,'釘蟲','data2\rom\eny\eny3039.ROM','data2\fight\eny\eny5039.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',43,'客戶端繁中文字串定位',1),
(40,40,'劊子蟲','data2\rom\eny\eny3040.ROM','data2\fight\eny\eny5040.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',44,'客戶端繁中文字串定位',1),
(41,41,'五點桃花駒','data2\rom\eny\eny3041.ROM','data2\fight\eny\eny5041.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',45,'客戶端繁中文字串定位',1),
(42,42,'黑麒麟','data2\rom\eny\eny3042.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',46,'客戶端怪物外觀身份定位',1),
(43,43,'四不像','data2\rom\eny\eny3043.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',47,'客戶端怪物外觀身份定位',1),
(44,44,'板角青牛','data2\rom\eny\eny3044.ROM','data2\fight\eny\eny5044.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',48,'客戶端怪物外觀身份定位',1),
(45,45,'五色神牛','data2\rom\eny\eny3045.ROM','data2\fight\eny\eny5045.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',49,'客戶端怪物外觀身份定位',1),
(46,46,'朱雀','data2\rom\eny\eny3046.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',50,'客戶端怪物外觀身份定位',1),
(47,47,'鯨龍','data2\rom\eny\eny3047.ROM','data2\fight\eny\eny5047.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',51,'客戶端繁中文字串定位',1),
(48,48,'神鯨','data2\rom\eny\eny3048.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',52,'客戶端繁中文字串定位',1),
(49,49,'蒼鯨','data2\rom\eny\eny3049.ROM','data2\fight\eny\eny5049.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',53,'客戶端繁中文字串定位',1),
(50,50,'狼','data2\rom\eny\eny3050.ROM','data2\fight\eny\eny5050.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',54,'客戶端怪物外觀身份定位',1),
(51,51,'豹','data2\rom\eny\eny3051.ROM','data2\fight\eny\eny5051.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',55,'客戶端怪物外觀身份定位',1),
(52,52,'熊','data2\rom\eny\eny3052.ROM','data2\fight\eny\eny5052.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',56,'客戶端怪物外觀身份定位',1),
(53,53,'虎','data2\rom\eny\eny3053.ROM','data2\fight\eny\eny5053.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',57,'客戶端怪物外觀身份定位',1),
(54,54,'穿山甲','data2\rom\eny\eny3054.ROM','data2\fight\eny\eny5054.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',58,'客戶端怪物外觀身份定位',1),
(55,55,'馬賊','data2\rom\eny\eny3055.ROM','data2\fight\eny\eny5055.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',59,'客戶端怪物外觀身份定位',1),
(56,56,'強熊','data2\rom\eny\eny3056.ROM','data2\fight\eny\eny5056.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',60,'客戶端繁中文字串定位',1),
(57,57,'粘濕','data2\rom\eny\eny3057.ROM','data2\fight\eny\eny5057.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',61,'客戶端繁中文字串定位',1),
(58,58,'苔怪','data2\rom\eny\eny3058.ROM','data2\fight\eny\eny5058.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',62,'客戶端怪物外觀身份定位',1),
(59,59,'藤蔓','data2\rom\eny\eny3059.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',63,'客戶端怪物外觀身份定位',1),
(60,60,'樹人','data2\rom\eny\eny3060.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',64,'客戶端怪物外觀身份定位',1),
(61,61,'雷電','data2\rom\eny\eny3061.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',65,'客戶端繁中文字串定位',1),
(62,62,'黑沙','data2\rom\eny\eny3062.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',66,'客戶端怪物外觀身份定位',1),
(63,63,'紅沙','data2\rom\eny\eny3063.ROM',NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',67,'客戶端怪物外觀身份定位',1),
(64,64,'通天教主',NULL,'data\fight\eny\eny6064.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',68,'客戶端怪物外觀身份定位',1),
(65,65,'秦天君',NULL,'data\fight\eny\eny6065.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',69,'客戶端怪物外觀身份定位',1),
(66,66,'趙天君',NULL,'data\fight\eny\eny6066.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',70,'客戶端怪物外觀身份定位',1),
(67,67,'孫天君',NULL,'data\fight\eny\eny6067.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',71,'客戶端怪物外觀身份定位',1),
(68,68,'張天君',NULL,'data\fight\eny\eny6068.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',72,'客戶端繁中文字串定位',1),
(69,69,'鏡子',NULL,'data\fight\eny\eny6069.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',73,'客戶端繁中文字串定位',1),
(70,70,'云霄三姊妹',NULL,'data\fight\eny\eny6070.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',74,'客戶端怪物外觀身份定位',1),
(71,71,'天將','data2\rom\eny\eny3071.ROM','data2\fight\eny\eny5071.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',75,'客戶端怪物外觀身份定位',1),
(72,72,'天兵','data2\rom\eny\eny3072.ROM','data2\fight\eny\eny5072.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',76,'客戶端怪物外觀身份定位',1),
(73,73,'董天君',NULL,'data\fight\eny\eny6073.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',77,'客戶端怪物外觀身份定位',1),
(74,74,'袁天君',NULL,'data\fight\eny\eny6074.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',78,'客戶端怪物外觀身份定位',1),
(75,75,'姚天君',NULL,'data\fight\eny\eny6075.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',79,'客戶端怪物外觀身份定位',1),
(76,76,'骷髏','data2\rom\eny\eny3076.ROM','data2\fight\eny\eny5076.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',80,'客戶端怪物外觀身份定位',1),
(77,77,'僵屍','data2\rom\eny\eny3077.ROM','data2\fight\eny\eny5077.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',81,'客戶端怪物外觀身份定位',1),
(78,78,'倩女','data2\rom\eny\eny3078.ROM','data2\fight\eny\eny5078.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',82,'客戶端怪物外觀身份定位',1),
(79,79,'麒麟','data2\rom\eny\eny3079.ROM','data2\fight\eny\eny5079.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',83,'客戶端怪物外觀身份定位',1),
(80,80,'青龍','data2\rom\eny\eny3080.ROM','data2\fight\eny\eny5080.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',84,'客戶端怪物外觀身份定位',1),
(81,81,'白虎','data2\rom\eny\eny3081.ROM','data2\fight\eny\eny5081.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',85,'客戶端怪物外觀身份定位',1),
(82,82,'朱雀','data2\rom\eny\eny3082.ROM','data2\fight\eny\eny5082.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',86,'客戶端怪物外觀身份定位',1),
(83,83,'玄武','data2\rom\eny\eny3083.ROM','data2\fight\eny\eny5083.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',87,'客戶端怪物外觀身份定位',1),
(84,84,'萬刃車','data2\rom\eny\eny3084.ROM','data2\fight\eny\eny6084.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',88,'客戶端繁中文字串定位',1),
(85,85,'白天君',NULL,'data\fight\eny\eny6085.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',89,'客戶端怪物外觀身份定位',1),
(86,86,'王天君',NULL,'data\fight\eny\eny6086.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',90,'客戶端怪物外觀身份定位',1),
(87,87,'幽魂','data2\rom\eny\eny3087.ROM','data2\fight\eny\eny5087.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',91,'客戶端怪物外觀身份定位',1),
(88,88,'楓樹怪','data2\rom\eny\eny3088.ROM','data2\fight\eny\eny5088.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',92,'客戶端繁中文字串定位',1),
(89,89,'蚌精','data2\rom\eny\eny3089.ROM','data2\fight\eny\eny5089.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',93,'客戶端怪物外觀身份定位',1),
(90,90,'山叉','data2\rom\eny\eny3090.ROM','data2\fight\eny\eny5090.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',94,'客戶端怪物外觀身份定位',1),
(91,91,'石頭鬼','data2\rom\eny\eny3091.ROM','data2\fight\eny\eny5091.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',95,'客戶端怪物外觀身份定位',1),
(92,92,'外觀怪物代碼 92','data2\rom\eny\eny3092.ROM','data2\fight\eny\eny5092.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',96,'客戶端怪物外觀身份定位',1),
(93,93,'外觀怪物代碼 93','data2\rom\eny\eny3093.ROM','data2\fight\eny\eny5093.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',97,'客戶端怪物外觀身份定位',1),
(94,94,'大年','data2\rom\eny\eny3094.ROM','data2\fight\eny\eny5094.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',98,'客戶端怪物外觀身份定位',1),
(95,95,'武吉',NULL,'data2\fight\eny\eny6095.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',99,'客戶端怪物外觀身份定位',1),
(96,96,'張奎','data2\rom\eny\eny3096.ROM','data2\fight\eny\eny6096.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',100,'客戶端繁中文字串定位',1),
(97,97,'高蘭英','data2\rom\eny\eny3097.ROM','data2\fight\eny\eny6097.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',101,'客戶端繁中文字串定位',1),
(98,98,'鄧嬋玉','data2\rom\eny\eny3098.ROM','data2\fight\eny\eny5098.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',102,'客戶端怪物外觀身份定位',1),
(99,99,'慈航道人',NULL,'data2\fight\eny\eny6099.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',103,'客戶端怪物外觀身份定位',1),
(100,100,'玉鼎真人',NULL,'data2\fight\eny\eny6100.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',104,'客戶端怪物外觀身份定位',1),
(101,101,'石磯娘娘',NULL,'data2\fight\eny\eny6101.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',105,'客戶端繁中文字串定位',1),
(102,102,'陽任',NULL,'data2\fight\eny\eny6102.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',106,'客戶端繁中文字串定位',1),
(103,103,'李靖','data2\rom\eny\eny3103.ROM','data2\fight\eny\eny5103.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',107,'客戶端怪物外觀身份定位',1),
(104,104,'崇黑虎',NULL,'data2\fight\eny\eny6104.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',108,'客戶端怪物外觀身份定位',1),
(105,105,'金光聖母',NULL,'data2\fight\eny\eny6105.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',109,'客戶端怪物外觀身份定位',1),
(106,106,'赤精子','data2\rom\eny\eny3106.ROM','data2\fight\eny\eny5106.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',110,'客戶端怪物外觀身份定位',1),
(107,107,'土行孫','data2\rom\eny\eny3107.ROM','data2\fight\eny\eny5107.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',111,'客戶端怪物外觀身份定位',1),
(108,108,'云中子',NULL,'data2\fight\eny\eny6108.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',112,'客戶端怪物外觀身份定位',1),
(109,109,'普賢真人',NULL,'data2\fight\eny\eny6109.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',113,'客戶端繁中文字串定位',1),
(110,110,'哪咤','data2\rom\eny\eny3110.ROM','data2\fight\eny\eny5110.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',114,'客戶端怪物外觀身份定位',1),
(111,111,'楊戩','data2\rom\eny\eny3111.ROM','data2\fight\eny\eny6111.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',115,'客戶端怪物外觀身份定位',1),
(112,112,'黃天化','data2\rom\eny\eny3112.ROM','data2\fight\eny\eny5112.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',116,'客戶端繁中文字串定位',1),
(113,113,'趙公明',NULL,'data2\fight\eny\eny6109.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',117,'客戶端怪物外觀身份定位',1),
(114,114,'龍吉公主',NULL,'data2\fight\eny\eny6109.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',118,'客戶端怪物外觀身份定位',1),
(115,115,'云霄三姊妹',NULL,'data2\fight\eny\eny6115.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',119,'客戶端怪物外觀身份定位',1),
(116,116,'姜子牙','data2\rom\eny\eny3116.ROM','data2\fight\eny\eny6116.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',120,'客戶端怪物外觀身份定位',1),
(117,117,'聞仲','data2\rom\eny\eny3117.ROM','data2\fight\eny\eny5117.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',121,'客戶端繁中文字串定位',1),
(118,118,'黃飛虎','data2\rom\eny\eny3118.ROM','data2\fight\eny\eny5118.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',122,'客戶端繁中文字串定位',1),
(119,119,'申公豹',NULL,'data2\fight\eny\eny6109.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',123,'客戶端怪物外觀身份定位',1),
(120,120,'太乙真人',NULL,'data2\fight\eny\eny6109.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',124,'客戶端怪物外觀身份定位',1),
(121,121,'雷震子','data2\rom\eny\eny3121.ROM','data2\fight\eny\eny5121.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',125,'客戶端怪物外觀身份定位',1),
(122,122,'胡喜媚',NULL,'data2\fight\eny\eny5122.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',126,'客戶端怪物外觀身份定位',1),
(123,123,'王貴人',NULL,'data2\fight\eny\eny6109.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',127,'客戶端繁中文字串定位',1),
(124,124,'妲己',NULL,'data2\fight\eny\eny6124.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',128,'客戶端怪物外觀身份定位',1),
(125,125,'拳頭師傅','data2\rom\eny\eny3125.ROM','data2\fight\eny\eny6125.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',129,'客戶端繁中文字串定位',1),
(126,126,'士兵','data2\rom\eny\eny3126.ROM','data2\fight\eny\eny5126.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',130,'客戶端怪物外觀身份定位',1),
(127,127,'黃帝',NULL,NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',131,'客戶端繁中文字串定位',1),
(128,128,'神農',NULL,NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',132,'客戶端繁中文字串定位',1),
(129,129,'伏羲',NULL,NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',133,'客戶端怪物外觀身份定位',1),
(130,130,'女媧',NULL,NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',134,'客戶端繁中文字串定位',1),
(131,131,'小小年','data2\rom\eny\eny3131.ROM','data2\fight\eny\eny5131.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',135,'客戶端怪物外觀身份定位',1),
(132,132,'蚩尤',NULL,NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',136,'客戶端怪物外觀身份定位',1),
(133,133,'盤古',NULL,NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',137,'客戶端繁中文字串定位',1),
(134,134,'紂王',NULL,NULL,'monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',138,'客戶端繁中文字串定位',1),
(135,135,'山賊頭目','data2\rom\eyn\eny3135.ROM','data2\fight\ey5n\eny5135.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',139,'客戶端怪物外觀身份定位',1),
(136,136,'雪女','data2\rom\eyn2\eny3136.ROM','data2\fight\ey5n2\eny5136.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',140,'客戶端怪物外觀身份定位',1),
(137,137,'盜賊騎兵','data2\rom\eyn\eny3137.ROM','data2\fight\ey5n\eny5137.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',141,'客戶端怪物外觀身份定位',1),
(138,138,'人類騎兵','data2\rom\eyn\eny3138.ROM','data2\fight\ey5n\eny5138.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',142,'客戶端怪物外觀身份定位',1),
(139,139,'禿鷹','data2\rom\eyn\eny3139.ROM','data2\fight\ey5n\eny5139.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',143,'客戶端繁中文字串定位',1),
(140,140,'野豬','data2\rom\eyn\eny3140.ROM','data2\fight\ey5n\eny5140.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',144,'客戶端怪物外觀身份定位',1),
(141,141,'雉雞','data2\rom\eyn\eny3141.ROM','data2\fight\ey5n\eny5141.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',145,'客戶端怪物外觀身份定位',1),
(142,142,'大角羊','data2\rom\eyn\eny3142.ROM','data2\fight\ey5n\eny5142.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',146,'客戶端怪物外觀身份定位',1),
(143,143,'牦牛','data2\rom\eyn2\eny3143.ROM','data2\fight\ey5n2\eny5143.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',147,'客戶端怪物外觀身份定位',1),
(144,144,'大熊','data2\rom\eyn2\eny3144.ROM','data2\fight\ey5n2\eny5144.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',148,'客戶端怪物外觀身份定位',1),
(145,145,'雪怪','data2\rom\eyn2\eny3145.ROM','data2\fight\ey5n2\eny5145.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',149,'客戶端怪物外觀身份定位',1),
(146,146,'企鵝','data2\rom\eyn2\eny3146.ROM','data2\fight\ey5n2\eny5146.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',150,'客戶端怪物外觀身份定位',1),
(147,147,'企鵝騎海豹','data2\rom\eyn2\eny3147.ROM','data2\fight\ey5n2\eny5147.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',151,'客戶端怪物外觀身份定位',1),
(148,148,'海豹','data2\rom\eyn2\eny3148.ROM','data2\fight\ey5n2\eny5148.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',152,'客戶端怪物外觀身份定位',1),
(149,149,'聖誕老人','data2\rom\eny\eny3149.ROM','data2\fight\eny\eny5149.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',153,'客戶端繁中文字串定位',1),
(150,150,'巨象','data2\rom\eyjiuwe\eny3150.ROM','data2\fight\Ey5jiuwe\eny5150.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',154,'客戶端怪物外觀身份定位',1),
(151,151,'始祖鳥','data2\rom\eyjiuwe\eny3151.ROM','data2\fight\Ey5jiuwe\eny5151.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',155,'客戶端怪物外觀身份定位',1),
(152,152,'瓢蟲','data2\rom\eyjiu\eny3152.ROM','data2\fight\ey5jiu\eny5152.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',156,'客戶端怪物外觀身份定位',1),
(153,153,'甲蟲','data2\rom\eyjiu\eny3153.ROM','data2\fight\ey5jiu\eny5153.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',157,'客戶端怪物外觀身份定位',1),
(154,154,'蜘蛛','data2\rom\eyjiu\eny3154.ROM','data2\fight\ey5jiu\eny5154.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',158,'客戶端怪物外觀身份定位',1),
(155,155,'蝸牛','data2\rom\eyjiu\eny3155.ROM','data2\fight\ey5jiu\eny5155.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',159,'客戶端繁中文字串定位',1),
(156,156,'神鬼戰士限定版','data2\rom\eyjiu\eny3156.ROM','data2\fight\ey5jiu\eny5156.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',160,'客戶端怪物外觀身份定位',1),
(157,157,'長毛雪怪','data2\rom\eyjiuwe\eny3157.ROM','data2\fight\Ey5jiuwe\eny5157.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',161,'客戶端怪物外觀身份定位',1),
(158,158,'烏拉草','data2\rom\eyjiuwe\eny3158.ROM','data2\fight\Ey5jiuwe\eny5158.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',162,'客戶端繁中文字串定位',1),
(159,159,'低等蛇族','data2\rom\eyjiu\eny3159.ROM','data2\fight\ey5jiu\eny5159.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',163,'客戶端怪物外觀身份定位',1),
(160,160,'蛇族女王','data2\rom\eyjiu\eny3160.ROM','data2\fight\ey5jiu\eny5160.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',164,'客戶端怪物外觀身份定位',1),
(161,161,'木制機關人','data2\rom\eyjiu\eny3161.ROM','data2\fight\ey5jiu\eny5161.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',165,'客戶端繁中文字串定位',1),
(162,162,'九黎國主教','data2\rom\eyjiu\eny3162.ROM','data2\fight\ey5jiu\eny5162.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',166,'客戶端繁中文字串定位',1),
(163,163,'黑衣人','data2\rom\eyjiu\eny3163.ROM','data2\fight\ey5jiu\eny5163.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',167,'客戶端怪物外觀身份定位',1),
(164,164,'蛇族骷髏護衛','data2\rom\eyjiu\eny3164.ROM','data2\fight\ey5jiu\eny5164.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',168,'客戶端繁中文字串定位',1),
(165,165,'雪貂','data2\rom\eyjiuwe\eny3165.ROM','data2\fight\Ey5jiuwe\eny5165.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',169,'客戶端怪物外觀身份定位',1),
(166,166,'狐族侍衛','data2\rom\eyjiuwe\eny3166.ROM','data2\fight\Ey5jiuwe\eny5166.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',170,'客戶端繁中文字串定位',1),
(167,167,'狼王','data2\rom\eyjiuwe\eny3167.ROM','data2\fight\Ey5jiuwe\eny5167.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',171,'客戶端怪物外觀身份定位',1),
(168,168,'雪女','data2\rom\eyjiuwe\eny3168.ROM','data2\fight\Ey5jiuwe\eny5168.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',172,'客戶端怪物外觀身份定位',1),
(169,169,'五尾魔王','data2\rom\eyjiuwe\eny3169.ROM','data2\fight\Ey5jiuwe\eny5169.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',173,'客戶端怪物外觀身份定位',1),
(170,170,'七尾魔王','data2\rom\eyjiuwe\eny3170.ROM','data2\fight\Ey5jiuwe\eny5170.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',174,'客戶端怪物外觀身份定位',1),
(171,171,'熾磷戰騎','data2\rom\eyjiuwe\eny3171.ROM','data2\fight\Ey5jiuwe\eny5171.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',175,'客戶端怪物外觀身份定位',1),
(172,172,'酷夏小熊熊','data2\rom\eyjiuwe\eny3172.ROM','data2\fight\Ey5jiuwe\eny5172.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',176,'客戶端怪物外觀身份定位',1),
(173,173,'白天君','data2\rom\Eny\eny3173.ROM','data2\fight\Eny\eny5173.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',177,'客戶端怪物外觀身份定位',1),
(174,174,'姚天君','data2\rom\Eny\eny3174.ROM','data2\fight\Eny\eny5174.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',178,'客戶端怪物外觀身份定位',1),
(175,175,'秦天君','data2\rom\Eny\eny3175.ROM','data2\fight\Eny\eny5175.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',179,'客戶端怪物外觀身份定位',1),
(176,176,'袁天君','data2\rom\Eny\eny3176.ROM','data2\fight\Eny\eny5176.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',180,'客戶端怪物外觀身份定位',1),
(177,177,'趙天君','data2\rom\Eny\eny3177.ROM','data2\fight\Eny\eny5177.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',181,'客戶端怪物外觀身份定位',1),
(178,178,'金鏡','data2\rom\Eny\eny3178.ROM','data2\fight\Eny\eny5178.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',182,'客戶端繁中文字串定位',1),
(179,179,'萬刃車','data2\rom\Eny\eny3179.ROM','data2\fight\Eny\eny5179.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',183,'客戶端繁中文字串定位',1),
(180,180,'彭遵','data2\rom\Eny\eny3180.ROM','data2\fight\Eny\eny5180.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',184,'客戶端怪物外觀身份定位',1),
(181,181,'董天君','data2\rom\Eny\eny3181.ROM','data2\fight\Eny\eny5181.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',185,'客戶端怪物外觀身份定位',1),
(182,182,'張天君','data2\rom\Eny\eny3182.ROM','data2\fight\Eny\eny5182.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',186,'客戶端繁中文字串定位',1),
(183,183,'狐貍祭司','data2\rom\Eny\eny3183.ROM','data2\fight\Eny\eny5183.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',187,'客戶端繁中文字串定位',1),
(184,184,'狐貍','data2\rom\Eny\eny3184.ROM','data2\fight\Eny\eny5184.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',188,'客戶端繁中文字串定位',1),
(185,185,'狐貍小丑','data2\rom\Eny\eny3185.ROM','data2\fight\Eny\eny5185.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',189,'客戶端繁中文字串定位',1),
(186,186,'千年人蔘','data2\rom\Eny\eny3186.ROM','data2\fight\Eny\eny5186.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',190,'客戶端怪物外觀身份定位',1),
(187,187,'武術宗師','data2\rom\Eny\eny3187.ROM','data2\fight\Eny\eny5187.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',191,'客戶端繁中文字串定位',1),
(188,188,'果力新兵器原型','data2\rom\Eny\eny3188.ROM','data2\fight\Eny\eny5188.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',192,'客戶端怪物外觀身份定位',1),
(189,189,'煌星髏虎','data2\rom\Eny\eny3189.ROM','data2\fight\Eny\eny5189.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',193,'客戶端怪物外觀身份定位',1),
(190,190,'飛魂魘蛇','data2\rom\Eny\eny3190.ROM','data2\fight\Eny\eny5190.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',194,'客戶端繁中文字串定位',1),
(191,191,'骨灰壇','data2\rom\Eny\eny3191.ROM','data2\fight\Eny\eny5191.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',195,'客戶端繁中文字串定位',1),
(192,192,'棺木怪','data2\rom\Eny\eny3192.ROM','data2\fight\Eny\eny5192.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',196,'客戶端怪物外觀身份定位',1),
(193,193,'骷髏豹','data2\rom\Eny\eny3193.ROM','data2\fight\Eny\eny5193.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',197,'客戶端怪物外觀身份定位',1),
(194,194,'骷髏狗','data2\rom\Eny\eny3194.ROM','data2\fight\Eny\eny5194.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',198,'客戶端怪物外觀身份定位',1),
(195,195,'骷髏羊','data2\rom\Eny\eny3195.ROM','data2\fight\Eny\eny5195.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',199,'客戶端怪物外觀身份定位',1),
(196,196,'蝙蝠','data2\rom\Eny\eny3196.ROM','data2\fight\Eny\eny5196.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',200,'客戶端怪物外觀身份定位',1),
(197,197,'無尾狼','data2\rom\Eny\eny3197.ROM','data2\fight\Eny\eny5197.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',201,'客戶端繁中文字串定位',1),
(198,198,'神秘寶樹(大陸用)','data2\rom\Eny\eny3198.ROM','data2\fight\Eny\eny5198.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',202,'客戶端繁中文字串定位',1),
(199,199,'大主教','data2\rom\Eny\eny3199.ROM','data2\fight\Eny\eny5199.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',203,'客戶端怪物外觀身份定位',1),
(200,200,'相撲手','data2\rom\Eny\eny3200.ROM','data2\fight\Eny\eny5200.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',204,'客戶端繁中文字串定位',1),
(201,201,'馬面','data2\rom\Eny\eny3201.ROM','data2\fight\Eny\eny5201.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',205,'客戶端怪物外觀身份定位',1),
(202,202,'犀牛','data2\rom\Eny\eny3202.ROM','data2\fight\Eny\eny5202.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',206,'客戶端怪物外觀身份定位',1),
(203,203,'兔子武士','data2\rom\Eny\eny3203.ROM','data2\fight\Eny\eny5203.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',207,'客戶端怪物外觀身份定位',1),
(204,204,'斧頭幫高','data2\rom\Eny\eny3204.ROM','data2\fight\Eny\eny5204.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',208,'客戶端怪物外觀身份定位',1),
(205,205,'斧頭幫矮','data2\rom\Eny\eny3205.ROM','data2\fight\Eny\eny5205.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',209,'客戶端怪物外觀身份定位',1),
(206,206,'火星大王','data2\rom\Eny\eny3206.ROM','data2\fight\Eny\eny5206.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',210,'客戶端怪物外觀身份定位',1),
(207,207,'蛇','data2\rom\Eny\eny3207.ROM','data2\fight\Eny\eny5207.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',211,'客戶端怪物外觀身份定位',1),
(208,208,'大頭馬','data2\rom\Eny\eny3208.ROM','data2\fight\Eny\eny5208.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',212,'客戶端怪物外觀身份定位',1),
(209,209,'大頭牛','data2\rom\Eny\eny3209.ROM','data2\fight\Eny\eny5209.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',213,'客戶端怪物外觀身份定位',1),
(210,210,'萬仞車','data2\rom\Eny\eny3210.ROM','data2\fight\Eny\eny5210.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',214,'客戶端繁中文字串定位',1),
(211,211,'黑V熊','data2\rom\Eny\eny3211.ROM','data2\fight\Eny\eny5211.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',215,'客戶端怪物外觀身份定位',1),
(212,212,'熔巖怪','data2\rom\Eny\eny3212.ROM','data2\fight\Eny\eny5212.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',216,'客戶端繁中文字串定位',1),
(213,213,'石獅子','data2\rom\Eny\eny3213.ROM','data2\fight\Eny\eny5213.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',217,'客戶端怪物外觀身份定位',1),
(214,214,'室火豬','data2\rom\Eny\eny3214.ROM','data2\fight\Eny\eny5214.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',218,'客戶端怪物外觀身份定位',1),
(215,215,'紅孩兒','data2\rom\Eny\eny3215.ROM','data2\fight\Eny\eny5215.rom','monster_skill','怪物技能欄位與效果','monster_skill_capture','server_implementation/data/evidence_raw/eny.csv|server_implementation/data/evidence_raw/FightEny.csv',219,'客戶端繁中文字串定位',1);

UPDATE god2_research.xjz_monster_skill_probe_targets target
JOIN god2_game.monsters monster
  ON monster.code = CONCAT('monster_', target.monster_code)
SET target.formal_monster_id = monster.monster_id,
    target.formal_monster_name_zh_tw = monster.name_zh_tw,
    target.formal_link_status_zh_tw = '已連結正式怪物';

UPDATE god2_research.xjz_monster_skill_probe_targets
SET formal_link_status_zh_tw = '正式怪物未建立'
WHERE formal_monster_id IS NULL;

CREATE OR REPLACE VIEW god2_research.vw_xjz_monster_skill_probe_targets_readable AS
SELECT
  probe_id,
  monster_code,
  COALESCE(formal_monster_name_zh_tw, monster_name_zh_tw) AS monster_name_zh_tw,
  field_rom_path,
  battle_rom_path,
  '怪物戰鬥技能' AS game_function_zh_tw,
  wanted_fields_zh_tw,
  CASE needs_packet_evidence WHEN 1 THEN '需要抓包或黑箱測試' ELSE '已可套用' END AS evidence_need_zh_tw,
  evidence_status_zh_tw,
  formal_monster_id,
  formal_link_status_zh_tw,
  source_file,
  source_line
FROM god2_research.xjz_monster_skill_probe_targets;

INSERT INTO god2_research.static_gap_remediation_queue
  (legacy_table_name, formal_table_name, priority_rank, remediation_category_zh_tw,
   game_function_zh_tw, evidence_policy_zh_tw, remediation_action_zh_tw,
   dependency_check_zh_tw, current_status_zh_tw, safe_to_apply_automatically,
   safe_to_drop_legacy_now, reviewed_at_utc)
VALUES
  ('xjz_monster_skill_probe_targets', 'monster_skills', 40, '補證清單',
   '怪物戰鬥技能',
   '客戶端還原只能證明需補測的怪物身份，不能直接證明技能 ID、觸發條件或使用機率。',
   '使用 xjz_monster_skill_probe_targets 對 215 隻怪物補抓技能欄位、技能效果、使用機率與觸發條件；證據來源為 XJZ C# 客戶端還原 monster_skill_probe_template；未確認前不啟用正式 monster_skills。',
   '已確認正式 monster_skills 需要 monster_id 與 skill_id 外鍵；目前只建立補證清單，不寫入正式技能表。',
   '已建立怪物技能抓包目標，正式技能仍待證據',
   0, 0, UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE
  priority_rank = VALUES(priority_rank),
  remediation_category_zh_tw = VALUES(remediation_category_zh_tw),
  game_function_zh_tw = VALUES(game_function_zh_tw),
  evidence_policy_zh_tw = VALUES(evidence_policy_zh_tw),
  remediation_action_zh_tw = VALUES(remediation_action_zh_tw),
  dependency_check_zh_tw = VALUES(dependency_check_zh_tw),
  current_status_zh_tw = VALUES(current_status_zh_tw),
  safe_to_apply_automatically = VALUES(safe_to_apply_automatically),
  safe_to_drop_legacy_now = VALUES(safe_to_drop_legacy_now),
  reviewed_at_utc = VALUES(reviewed_at_utc);

UPDATE god2_research.formal_table_server_correspondence
SET server_correspondence_status_zh_tw = '服務端表存在；已補抓包目標，正式資料待技能證據',
    runtime_usage_policy_zh_tw = 'monster_skills 只有在技能 ID、觸發條件與機率有證據或服主設計規則後才能啟用。',
    cleanup_decision_zh_tw = '保留正式空表；用 xjz_monster_skill_probe_targets 作為補證清單。',
    reviewed_at_utc = UTC_TIMESTAMP(6)
WHERE schema_name = 'god2_game' AND table_name = 'monster_skills';
