UPDATE god2_research.xjz_npc_dialog_candidates
SET speaker_or_branch_zh_tw = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                               speaker_or_branch_zh_tw,
                               '温', '溫'),
                               '烦', '煩'),
                               '恼', '惱'),
                               '长', '長'),
                               '马', '馬'),
                               '增强', '增強'),
                               '防御', '防禦'),
                               '说话', '說話'),
                               '话', '話'),
                               '探测', '探測'),
                               '雷达', '雷達'),
                               '两', '兩'),
                               '颗', '顆'),
                               '渐', '漸'),
                               '顶', '頂'),
                               '分别', '分別'),
                               '战报', '戰報'),
                               '东', '東'),
                               '状况', '狀況'),
                               '赶快', '趕快'),
                               '详细', '詳細'),
                               '威胁', '威脅'),
                               '难', '難'),
                               '主谋', '主謀'),
                               '联盟', '聯盟'),
                               '他们', '他們'),
                               '厉害', '厲害'),
                               '经过', '經過'),
                               '监', '監'),
                               '连络员', '聯絡員'),
                               '过去', '過去'),
                               '她们', '她們'),
                               '不过', '不過'),
                               '别', '別'),
                               '错', '錯'),
                               '测', '測'),
                               '达', '達'),
                               '报', '報'),
                               '过', '過'),
                               '联', '聯')
WHERE speaker_or_branch_zh_tw IS NOT NULL;
